# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d1cb76c3edf8db57b410e2d75268a14"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "dublicate-store"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
